#!/bin/sh -eux

## xcode command line tools install
# xcode-select --install
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install caskroom/cask/brew-cask
brew install rcmdnk/file/brew-file
brew file set_repo -r civitaspo/dotfiles
brew file install

brew link openssl --force
brew link curl --force
