#!/bin/sh -eux

XHOME=$(cd $(dirname $0)/..;pwd)

(
  cd $XHOME
  repo_url="git@github.com:civitaspo/dotfiles-secret.git"
  branch=$(git rev-parse --abbrev-ref HEAD)
  
  git ls-remote -h $repo_url | grep "refs/heads/$branch" > /dev/null 2>&1
  [ $? -ne 0 ] && branch=master
  
  if [ -d "dotfiles-secret/.git" ]; then
    (
    cd dotfiles-secret
      git fetch -p
      git checkout -q $branch
      latest_rev=$(git ls-remote origin HEAD | awk '{print $1}')
      current_rev=$(git rev-parse HEAD)
      [ "$latest_rev" != "$current_rev" ] && git pull origin $branch
    )
  else
    git clone -b $branch $repo_url dotfiles-secret
  fi
)
